version: '3'

tasks:
  default:
    desc: "Shows available tasks."
    cmds:
      - task --list-all

  up:
    desc: "Build images and start all services in detached mode."
    cmds:
      - echo "📦 running..."
      - docker-compose up -d --build

  start:
    desc: "Start existing containers."
    cmds:
      - echo "📦 running..."
      - docker-compose start

  stop:
    desc: "Stop running services."
    cmds:
      - echo "📦 running..."
      - docker-compose stop

  down:
    desc: "Stop and remove containers."
    cmds:
      - echo "📦 running..."
      - docker-compose down

  restart:
    desc: "Stops and builds the containers."
    cmds:
      - echo "📦 running..."
      - docker-compose down && docker-compose up -d --build

  clean:
    desc: "Stop, remove containers, networks and data volumes."
    prompt: "Are you sure? (y/n)"
    cmds:
      - echo "📦 running..."
      - docker-compose down -v

  ps:
    desc: "Show status of containers."
    cmds:
      - echo "📦 running..."
      - docker-compose ps